version: "3.8"
services:
    postgres:
        image: postgres:latest
        restart: always
        environment: #for testing only
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=rootpassword
        ports:
            - "5432:5432"
        volumes:
            - ./postgres/db-seed.sql:/docker-entrypoint-initdb.d/db-seed.sql # seed db with fake data
            - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql # create role for vault
    vault:
        hostname: vault
        container_name: vault
        depends_on:
            # Our app needs database so db needs to be loaded first
            - postgres
        image: hashicorp/vault:latest
        environment:
            VAULT_ADDR: "http://0.0.0.0:8200"
            VAULT_API_ADDR: "http://0.0.0.0:8200"
        ports:
            - "8200:8200"
        volumes:
            - ./volumes/vault/file:/vault/file:rw
        cap_add:
            - IPC_LOCK
        entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"
        # UI can be accessed via http://localhost:8200/ui in dev mode, ui is enabled by default. access method will be token and pw is "root"

    vault-init-tf:
        container_name: vault-init-tf
        image: hashicorp/terraform:latest
        volumes:
            - ./terraform/:/terraform
            - ./vault-config/readonly.sql:/vault-config/readonly.sql
            - ./app-backend:/app # for outputting the approle ids
        depends_on:
            - vault
        restart: "no"
        working_dir: terraform/
        environment:
            VAULT_ADDR: http://vault:8200
            VAULT_TOKEN: root
        entrypoint: >
            sh -c "terraform init && terraform apply -auto-approve"

    app-backend:
        build: ./app-backend # ensure the Dockerfile is in the current directory
        depends_on:
            # Our app needs database so db needs to be loaded first
            - postgres
            - vault-init-tf
        ports:
            - "3000:8080"
        volumes:
            - ./app-backend:/usr/src/app
        command: /bin/bash -c "sleep 5 && npm start"
